#!/usr/bin/env bash
# Bootstrap OpenPineBuds SDK + ARM GCC toolchain for this workspace.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

TOOLS_DIR="${TOOLS_DIR:-$ROOT/.tools}"
VENDOR_DIR="${VENDOR_DIR:-$ROOT/vendor}"
GCC_VER="gcc-arm-none-eabi-9-2019-q4-major"
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64) GCC_ARCH="x86_64" ;;
  aarch64|arm64) GCC_ARCH="aarch64" ;;
  *)
    echo "Unsupported arch: $ARCH" >&2
    exit 1
    ;;
esac

GCC_URL="https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2019q4/${GCC_VER}-${GCC_ARCH}-linux.tar.bz2"
OPENPINEBUDS_URL="${OPENPINEBUDS_URL:-https://github.com/pine64/OpenPineBuds.git}"
OPENPINEBUDS_REF="${OPENPINEBUDS_REF:-main}"

mkdir -p "$TOOLS_DIR" "$VENDOR_DIR"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

need_cmd curl
need_cmd tar
need_cmd git
need_cmd make

echo "==> Ensuring host packages (best effort)"
if command -v apt-get >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    build-essential bc xxd bzip2 ffmpeg clang-format pkg-config libudev-dev \
    >/dev/null
fi

if [[ ! -x "$TOOLS_DIR/$GCC_VER/bin/arm-none-eabi-gcc" ]]; then
  echo "==> Downloading $GCC_VER ($GCC_ARCH)"
  tmp="$(mktemp -d)"
  curl -fsSL "$GCC_URL" -o "$tmp/gcc.tar.bz2"
  tar -xjf "$tmp/gcc.tar.bz2" -C "$TOOLS_DIR"
  rm -rf "$tmp"
else
  echo "==> ARM GCC already present"
fi

export PATH="$TOOLS_DIR/$GCC_VER/bin:$PATH"
arm-none-eabi-gcc --version | head -1

if [[ ! -d "$VENDOR_DIR/OpenPineBuds/.git" ]]; then
  echo "==> Cloning OpenPineBuds ($OPENPINEBUDS_REF)"
  git clone --depth 1 --branch "$OPENPINEBUDS_REF" "$OPENPINEBUDS_URL" "$VENDOR_DIR/OpenPineBuds"
else
  echo "==> OpenPineBuds already cloned"
fi

# Sync experimental loopback sources into the vendored SDK (overwrite each bootstrap).
if [[ -d "$ROOT/firmware/stage_a" ]]; then
  echo "==> Syncing firmware/stage_a -> vendor/OpenPineBuds/apps/cros_loopback"
  mkdir -p "$VENDOR_DIR/OpenPineBuds/apps/cros_loopback"
  cp -f "$ROOT/firmware/stage_a/cros_loopback.c" \
        "$ROOT/firmware/stage_a/cros_loopback.h" \
        "$ROOT/firmware/stage_a/Makefile" \
        "$VENDOR_DIR/OpenPineBuds/apps/cros_loopback/"
fi

# Sync Stage B cross-bud CROS sources.
if [[ -d "$ROOT/firmware/stage_b" ]]; then
  echo "==> Syncing firmware/stage_b -> vendor/OpenPineBuds/apps/cros_tws"
  mkdir -p "$VENDOR_DIR/OpenPineBuds/apps/cros_tws"
  cp -f "$ROOT/firmware/stage_b/cros_tws.c" \
        "$ROOT/firmware/stage_b/cros_tws.h" \
        "$ROOT/firmware/stage_b/Makefile" \
        "$VENDOR_DIR/OpenPineBuds/apps/cros_tws/"
fi

# Apply local patches once we have them.

if [[ -d "$ROOT/patches" ]] && compgen -G "$ROOT/patches/*.patch" >/dev/null; then
  echo "==> Applying patches/"
  for p in "$ROOT/patches"/*.patch; do
    echo "    $p"
    git -C "$VENDOR_DIR/OpenPineBuds" apply --check "$p" 2>/dev/null \
      && git -C "$VENDOR_DIR/OpenPineBuds" apply "$p" \
      || git -C "$VENDOR_DIR/OpenPineBuds" apply --reverse --check "$p" >/dev/null 2>&1 \
      || echo "    (skip or already applied)"
  done
fi

# bestool is only required for USB flashing. Cloud Agent images rarely need it;
# set SKIP_BESTOOL=1 to skip, or leave unset to build when possible.
if [[ "${SKIP_BESTOOL:-0}" == "1" ]]; then
  echo "==> Skipping bestool (SKIP_BESTOOL=1)"
elif [[ -x "$TOOLS_DIR/bin/bestool" ]]; then
  echo "==> bestool already present"
else
  echo "==> Building bestool"
  if ! command -v cargo >/dev/null 2>&1 || [[ ! -f "$HOME/.cargo/env" ]]; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
  fi
  if [[ -f "$HOME/.cargo/env" ]]; then
    # shellcheck disable=SC1091
    source "$HOME/.cargo/env"
  fi
  if ! command -v cargo >/dev/null 2>&1; then
    echo "WARNING: cargo not available; skipping bestool (firmware build still works)" >&2
  else
    # bestool needs edition2024-capable Cargo (1.85+); keep stable current.
    rustup update stable >/dev/null
    rustup default stable >/dev/null
    mkdir -p "$TOOLS_DIR/bin"
    bestool_src="$TOOLS_DIR/bestool-src"
    if [[ ! -d "$bestool_src/.git" ]]; then
      git clone --depth 1 https://github.com/Ralim/bestool.git "$bestool_src"
    fi
    (cd "$bestool_src/bestool" && cargo build --release)
    cp "$bestool_src/bestool/target/release/bestool" "$TOOLS_DIR/bin/bestool"
  fi
fi

# Env helper for subsequent scripts
cat > "$TOOLS_DIR/env.sh" <<EOF
# Generated by scripts/bootstrap-sdk.sh
export PINEBUDS_ROOT="$ROOT"
export OPENPINEBUDS_ROOT="$VENDOR_DIR/OpenPineBuds"
export PATH="$TOOLS_DIR/$GCC_VER/bin:$TOOLS_DIR/bin:\$PATH"
EOF

echo "==> Bootstrap complete"
echo "    source $TOOLS_DIR/env.sh"
echo "    ./scripts/build.sh"
